version: "3"
services:
  app:
    container_name: dev_rust_base_app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - USER=root
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./src:/var
      # - ./src/web:/var/www/html
    restart: always
    networks:
      - dev_rust_base_network

networks:
  dev_rust_base_network:
